spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost:3306/elecktra?characterEncoding=UTF-8&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: dev
    password: dev

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
